---
roles:
  - name: robertdebock.core_dependencies
    version: 2.1.5
  - name: robertdebock.java
    version: 4.1.1
  - name: geerlingguy.solr
    version: 5.3.2
  - name: robertdebock.service
    version: 3.1.2
  - name: robertdebock.tomcat
    version: 5.3.4
  - name: gantsign.maven
    version: 5.6.3
  - name: smierz.vivo
    src: https://github.com/smierz/ansible-role-vivo
    version: master
